version: 2
updates:

  # Submodules (hosts and adapters)

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "submodule:"

  # Runtimes (not synced with submodules)

  - package-ecosystem: "cargo"
    directory: "/test/runtimes/hostapi"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "hostapi-rt:"

  # GitHub Actions

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci:"
