version: 2
updates:

  # Submodules (hosts and some adapters)

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "submodule:"

  # Adapters (not handled by submodules)

  - package-ecosystem: "cargo"
    directory: "/test/adapters/substrate"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "substrate-a:"
    open-pull-requests-limit: 0

  # Runtimes (not handled by submodules)

  - package-ecosystem: "cargo"
    directory: "/test/runtimes/hostapi"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "hostapi-rt:"
    open-pull-requests-limit: 0

  - package-ecosystem: "cargo"
    directory: "/test/runtimes/tester"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "tester-rt:"
    open-pull-requests-limit: 0

  # GitHub Actions

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci:"
