name: Specification Publication

on:
  push:
    paths:
    - '.github/workflows/specification.yml'
    - '.github/apt-texmacs.asc'
    - 'host-spec/**'
    - 'runtime-spec/**'
  pull_request:
    paths:
    - '.github/workflows/specification.yml'
    - '.github/apt-texmacs.asc'
    - 'host-spec/**'
    - 'runtime-spec/**'
  release:
    types: [published]

jobs:
  build-spec-host:
    name: Compile host specification
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-key add .github/apt-texmacs.asc
        sudo add-apt-repository "deb http://ftp.texmacs.org/TeXmacs/tmftp/repos/apt/ focal universe"
        sudo apt-get update
        sudo apt-get install -y xvfb texmacs plantuml
    - name: Install TeXmacs pacakges
      run: |
        mkdir -p ~/.TeXmacs/packages
        cd ~/.TeXmacs/packages
        curl -OL https://raw.githubusercontent.com/w3f/algorithmacs/master/algorithmacs-style.ts
    - name: Build host specification
      run: make -C host-spec
    - name: Upload host specification
      uses: actions/upload-artifact@v1
      with:
        name: polkadot-host-spec.pdf
        path: host-spec/polkadot-host-spec.pdf
    - name: Release host specification
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: host-spec/polkadot-host-spec.pdf
        asset_name: polkadot-host-spec_${{ github.event.release.tag_name }}.pdf
        asset_content_type: application/pdf
      if: github.event_name == 'release'

  build-spec-runtime:
    name: Compile runtime specification
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive texlive-luatex texlive-science texlive-latex-extra
    - name: Build runtime specification
      run: make -C runtime-spec
    - name: Upload runtime specification
      uses: actions/upload-artifact@v1
      with:
        name: polkadot-runtime-spec.pdf
        path: runtime-spec/polkadot-runtime-spec.pdf
    - name: Release runtime specification
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: runtime-spec/polkadot-runtime-spec.pdf
        asset_name: polkadot-runtime-spec_${{ github.event.release.tag_name }}.pdf
        asset_content_type: application/pdf
      if: github.event_name == 'release'


  diff-spec-host:
    name: Compare host specification
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
      if: github.event_name == 'push'
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
      if: github.event_name == 'pull_request' || github.event_name == 'release'
    - name: Install dependencies
      run: |
        sudo apt-key add .github/apt-texmacs.asc
        sudo add-apt-repository "deb http://ftp.texmacs.org/TeXmacs/tmftp/repos/apt/ focal universe"
        sudo apt-get update
        sudo apt-get install -y xvfb texmacs plantuml
    - name: Install TeXmacs pacakges
      run: |
        mkdir -p ~/.TeXmacs/packages
        cd ~/.TeXmacs/packages
        curl -OL https://raw.githubusercontent.com/w3f/algorithmacs/master/algorithmacs-style.ts
    - name: Determine comparison target
      run: echo "::set-env name=REV::HEAD~1"
      if: github.event_name == 'push'
    - name: Determine comparison target
      run: echo "::set-env name=REV::origin/${GITHUB_BASE_REF}"
      if: github.event_name == 'pull_request'
    - name: Determine comparison target
      run: echo "::set-env name=REV::$(git describe --tags --abbrev=0 HEAD~1)"
      if: github.event_name == 'release'
    - name: Compare host specification
      run: make -C host-spec diff
    - name: Upload host specification diff
      uses: actions/upload-artifact@v2
      with:
        name: polkadot-host-spec.diff.pdf
        path: host-spec/polkadot-host-spec.diff.pdf
    - name: Release host specification diff
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: host-spec/polkadot-host-spec.diff.pdf
        asset_name: polkadot-host-spec_${{ github.event.release.tag_name }}.diff_${{ env.REV }}.pdf
        asset_content_type: application/pdf
      if: github.event_name == 'release'
